name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.1

  build:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build
      run: |
        ruby extconf.rb
        make
    - name: Run the test suite
      run: |
        rake
